import type { ExerciseDefinition, RoutineDefinition } from './models'

export const routines: RoutineDefinition[] = [
  {
    id: 'day-1',
    name: 'Day 1',
    focus: 'Lower A',
    exercises: [
      { id: 'barbell-squat', name: 'Barbell Squat', prescription: '4 x 6-8', defaultSets: 4 },
      { id: 'romanian-deadlift', name: 'Romanian Deadlift', prescription: '3 x 8-10', defaultSets: 3 },
      { id: 'dumbbell-lunges', name: 'Dumbbell Lunges', prescription: '3 x 8-10 per leg', defaultSets: 3 },
      { id: 'dumbbell-step-up', name: 'Dumbbell Step-Up', prescription: '3 x 8-12 per leg', defaultSets: 3 },
      { id: 'calf-raises', name: 'Calf Raises', prescription: '3 x 12-15', defaultSets: 3 },
      { id: 'plank', name: 'Plank', prescription: '3 x 30-45 seconds', defaultSets: 3, unit: 'sec' },
    ],
  },
  {
    id: 'day-2',
    name: 'Day 2',
    focus: 'Upper A',
    exercises: [
      {
        id: 'barbell-bench-press',
        name: 'Barbell Bench Press',
        prescription: '4 x 6-8',
        suggested: '30-40 kg',
        defaultSets: 4,
      },
      {
        id: 'one-arm-dumbbell-row',
        name: 'One-Arm Dumbbell Row',
        prescription: '3 x 8-12 per side',
        suggested: '14-20 kg',
        defaultSets: 3,
      },
      {
        id: 'incline-dumbbell-press',
        name: 'Incline Dumbbell Press',
        prescription: '3 x 8-10',
        suggested: '10-14 kg each',
        defaultSets: 3,
      },
      {
        id: 'pull-up',
        name: 'Pull-Up',
        prescription: '3 x 5-8',
        suggested: 'Bodyweight/assisted',
        defaultSets: 3,
      },
      {
        id: 'lateral-raises',
        name: 'Lateral Raises',
        prescription: '3 x 12-15',
        suggested: '4-7 kg each',
        defaultSets: 3,
      },
      {
        id: 'ez-bar-curl',
        name: 'EZ-Bar Curl',
        prescription: '2 x 10-12',
        suggested: '15-20 kg total',
        defaultSets: 2,
      },
      {
        id: 'cable-triceps-extension',
        name: 'Cable Triceps Extension',
        prescription: '2 x 10-12',
        suggested: 'RIR 1-2',
        defaultSets: 2,
      },
      {
        id: 'overhead-dumbbell-extension',
        name: 'Overhead Dumbbell Extension',
        prescription: '2 x 10-12',
        suggested: '10-14 kg',
        defaultSets: 2,
        optional: true,
      },
    ],
  },
  {
    id: 'day-3',
    name: 'Day 3',
    focus: 'Lower B',
    exercises: [
      {
        id: 'barbell-hip-thrust',
        name: 'Barbell Hip Thrust',
        prescription: '4 x 8-10',
        suggested: '40-60 kg',
        defaultSets: 4,
      },
      {
        id: 'leg-press',
        name: 'Leg Press',
        prescription: '3 x 8-12',
        suggested: '60-100 kg',
        defaultSets: 3,
      },
      { id: 'leg-curl', name: 'Leg Curl', prescription: '3 x 10-12', suggested: 'RIR 2', defaultSets: 3 },
      {
        id: 'bulgarian-split-squat',
        name: 'Bulgarian Split Squat',
        prescription: '3 x 8-10 per leg',
        suggested: '6-10 kg each',
        defaultSets: 3,
      },
      {
        id: 'hip-abduction',
        name: 'Hip Abduction / Lateral Kick',
        prescription: '2 x 12-15 per leg',
        suggested: 'RIR 2',
        defaultSets: 2,
      },
      {
        id: 'hip-adduction',
        name: 'Cable / Machine Hip Adduction',
        prescription: '2 x 12-15',
        suggested: 'RIR 2',
        defaultSets: 2,
      },
      {
        id: 'leg-raises',
        name: 'Leg / Knee Raises',
        prescription: '3 x 10-15',
        suggested: 'Bodyweight',
        defaultSets: 3,
      },
    ],
  },
  {
    id: 'day-4',
    name: 'Day 4',
    focus: 'Upper B',
    exercises: [
      {
        id: 'pull-up-lat-pulldown',
        name: 'Pull-Up or Lat Pulldown',
        prescription: '3 x 6-10',
        suggested: 'Bodyweight/assisted or RIR 2',
        defaultSets: 3,
      },
      {
        id: 'incline-barbell-press',
        name: 'Incline Barbell Press',
        prescription: '3 x 6-10',
        suggested: '25-35 kg',
        defaultSets: 3,
      },
      {
        id: 'barbell-row',
        name: 'Barbell Row',
        prescription: '3 x 8-10',
        suggested: '25-35 kg',
        defaultSets: 3,
      },
      { id: 'pec-deck', name: 'Pec Deck', prescription: '3 x 10-15', suggested: 'RIR 2', defaultSets: 3 },
      { id: 'face-pull', name: 'Face Pull', prescription: '3 x 12-15', suggested: 'RIR 2', defaultSets: 3 },
      {
        id: 'hammer-curl',
        name: 'Hammer Curl',
        prescription: '2 x 10-12',
        suggested: '7-10 kg each',
        defaultSets: 2,
      },
      {
        id: 'ez-bar-skull-crushers',
        name: 'EZ-Bar Skull Crushers',
        prescription: '2 x 10-12',
        suggested: '10-15 kg total',
        defaultSets: 2,
      },
    ],
  },
]

export const exerciseCatalog = new Map<string, ExerciseDefinition>(
  routines.flatMap((routine) => routine.exercises).map((exercise) => [exercise.id, exercise]),
)

export const legacyExerciseIds: Record<string, string> = {
  'Sentadilla con barra': 'barbell-squat',
  'Peso muerto rumano': 'romanian-deadlift',
  'Lunges con mancuernas': 'dumbbell-lunges',
  'Step-up con mancuernas': 'dumbbell-step-up',
  'Elevacion de pantorrillas': 'calf-raises',
  Plancha: 'plank',
  'Press banca con barra': 'barbell-bench-press',
  'Remo mancuerna a una mano': 'one-arm-dumbbell-row',
  'Press inclinado mancuernas': 'incline-dumbbell-press',
  'Pull-up': 'pull-up',
  'Elevaciones laterales': 'lateral-raises',
  'Curl con barra Z': 'ez-bar-curl',
  'Extension triceps polea': 'cable-triceps-extension',
  'Extension sobre cabeza con mancuerna': 'overhead-dumbbell-extension',
  'Hip thrust con barra': 'barbell-hip-thrust',
  Prensa: 'leg-press',
  'Curl femoral': 'leg-curl',
  'Bulgarian split squat': 'bulgarian-split-squat',
  'Abduccion/patada lateral': 'hip-abduction',
  'Aduccion en polea/maquina': 'hip-adduction',
  'Elevacion de piernas/rodillas': 'leg-raises',
  'Pull-up o jalon al pecho': 'pull-up-lat-pulldown',
  'Press inclinado con barra': 'incline-barbell-press',
  'Remo con barra al ombligo': 'barbell-row',
  'Pec deck': 'pec-deck',
  'Face pull': 'face-pull',
  'Curl martillo': 'hammer-curl',
  'Rompecraneos con barra Z': 'ez-bar-skull-crushers',
}
